### PR TITLE
Use CodeName to find entity fields fixes #240

### LINKED ISSUE #240: Errors running MJExplorer when there is a space in a column name
**Describe the bug**

Errors running MJExplorer when there is a space in a column name.

image

Seems to be that the code in `ng-base-forms` is using entity field `Name` to find fields instead of `CodeName` (i.e. comparing space-sanitized to original name).

### PR DESCRIPTION
**Pull request by cadam11**

### CODE REVIEW

File: packages/SQLServerDataProvider/src/SQLServerDataProvider.ts [hunk 1]
```diff
@@ -1883,14 +1883,14 @@ export class SQLServerDataProvider extends ProviderBase implements IEntityDataPr
             }
             else {
                 // got our field, create a SQL Query
-                let sql: string = `SELECT ${f.Name} FROM [${e.SchemaName}].[${e.BaseView}] WHERE `
+                let sql: string = `SELECT [${f.Name}] FROM [${e.SchemaName}].[${e.BaseView}] WHERE `
                 let where: string = '';
                 for (let pkv of CompositeKey.KeyValuePairs) {
                     const pk = e.PrimaryKeys.find(pk => pk.Name === pkv.FieldName);
```
Comment (cadam11) [inline packages/SQLServerDataProvider/src/SQLServerDataProvider.ts:1889]: In this case, I did not change it to use `CodeName` since (afaict) the `FieldName` value from the CompositeKey class would generally be the actual column name (with spaces)
