### PR TITLE
Fixes #222 - Only use AutoIncrement to signal entity whose PK should not be declared

### LINKED ISSUE #222: CodeGen: PK typed as uniqueidentifier isn't declared in generated SPs
When running CodeGen against a database with tables with a primary key that's typed `uniqueidentifier`, the primary key isn't included in the stored procedure declarations.

```
ERROR (Wed May 22 2024 17:21:39 GMT-0500 (Central Daylight Time): QueryFailedError: Error: Must declare the scalar variable "@ProductPriceLevelId".
```

### PR DESCRIPTION
**Pull request by cadam11**
For create entity SPs, we assign a `NEWID()` to a local variable that's used to create the new row:

```sql
    DECLARE @newId UNIQUEIDENTIFIER = NEWID();
    SET @ProductPriceLevelId = @newId;
```

However, the `autoGeneratedPrimaryKey` flag is set if `entity.PrimaryKey.Type.toLowerCase().trim() === 'uniqueidentifier'` which prevents that entity field from being included in the string generated by `createEntityFieldsParamString`.

The solution is to update the `generateSPCreate` function so that an entity is only tagged as having an `autoGeneratedPrimaryKey` if `entity.PrimaryKey.AutoIncrement` is true.

## Other changes

- This also uses `CodeName` where `Name` was used to avoid unescaped names.
- And removes the logic that prevents any `uniqueidentifier`-typed column from being updated (some FKs are typed this way)

### CODE REVIEW

File: packages/CodeGenLib/src/sql_codegen.ts [hunk 1]
```diff
@@ -833,8 +832,7 @@ GO${permissions}
               !ef.IsVirtual &&
               (!ef.IsPrimaryKey || !autoGeneratedPrimaryKey || isUpdate) &&
               ef.Name.toLowerCase().trim() !== 'updatedat' &&
-              ef.Name.toLowerCase().trim() !== 'createdat' &&
-              (ef.Type.toLowerCase().trim() !== 'uniqueidentifier' || ef.IsPrimaryKey)
```
Comment (cadam11) [inline packages/CodeGenLib/src/sql_codegen.ts:837]: @AN-BC This change was to overcome issues arising from not being able to update FK columns that are typed as `uniqueidentifier` (although they should probably be typed varchar). There may be Unintended Consequences here– would love your opinion on the change

Comment (AN-BC) [reply packages/CodeGenLib/src/sql_codegen.ts:837]: @cadam11 the removal of `createdat` is one I would reconsider, that field name has special meaning and shouldn't be passed into spCreate. As for the inclusion of uniqueidentifier columns into the spCreate, I wonder if we can use the `AllowUpdateAPI` flag on the EntityField record to determine if we include this in spCreate. For situations where the developer/sysadmin wants to allow uniqueidentifiers to be created by the client code and passed in, we can allow them in, but if `AllowUpdateAPI===0` then we don't include it, instead of checking the Primarykey flag?

Comment (cadam11) [reply packages/CodeGenLib/src/sql_codegen.ts:837]: This change doesn't remove `createdat`, just the `&& (ef.Type.toLowerCase().trim() !== 'uniqueidentifier' || ef.IsPrimaryKey)` clause.

It also does preserve the existing behavior for `AllowUpdateAPI` such that an entity field will only be included in the declaration if `AllowUpdateAPI` is set, or both `IsPrimaryKey` and `isUpdate` are true.

Sounds like this change is unlikely to introduce new, undesired behavior so I think we're ok to merge it.
